### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by antithing** [saihv/coloc#2]
Hi, and thanks for making this code available! I am using it as reference to build a simpler application, stereo camera slam using KORAL and CUDA2KNN.

I am matching points, creating a local map, then matching each incoming frame to the local map.

If you have a minute, could you help me out with a couple of things?

I see that you add mapData with:

```
void setMapData(int kpNum, void* desc)
		{
			cudaMemsetAsync(d_descM, 0, 64 * (kpNum + 8), m_stream1);
			cudaMemcpyAsync(d_descM, desc, 64 * (kpNum + 8), cudaMemcpyHostToDevice, m_stream1);
			cudaStreamSynchronize(m_stream1);

			this->kpMap = kpNum;
		}
```

that makes sense. My issue is, if I have keypoints and descriptors from my current frame, and I want to add a subset of these to the local map, how do I do that with the descriptors? 

Say that i have:

```
	std::vector <cv::KeyPoint> kpsR;
	std::vector<uint64_t> desc2;
```

And I only want to add the first 10 keypoints and descriptors to my local map.

I can just get the first 10 keypoints from the kpsL vector, but how do I do this with the descriptors, and add them to the map data as you do?

I am trying:

	std::vector<cv::KeyPoint> localMap_kp;
	std::vector<uint64_t> localMap_desc;

	int ii = 0;
	for (int i = 0; i < 10; i++)
	{
		for (int j = 0; j < 8; j++)
		{
			localMap_desc.push_back(desc2[ii + j]);
		}

		ii += 8;
		localMap_kp.push_back(kpsR[i]);

	}

	matcher.setMapData(localMap_kp.size(), localMap_desc);

     //match to this map
	detector.extractFeatures(img1);
	kpsL = detector.converted_kps;
	matcher.matchSceneWithMap(detector.kps, detector.desc);

But this is clearly wrong. What is the right way to do this?
Thank you very much for your time!

**Comment by saihv** [comment]
@antithing 

Essentially, the `64 * (kpNum + 8)` is defining how many bytes you want to memcpy from the location pointing to `desc`. Have you tried reading just the first 10 descriptors while copying? The syntax for memcpy would be

`memcpy( &dst[dstIdx], &src[srcIdx], numElementsToCopy * sizeof( Element ) );`

Any training matches need an extra 8 elements at the end, so for 10 keypoints I'd guess your size would have to be 64 * (10 + 8) for `desc`. Can you give this a shot?

EDIT: In your approach, what is `desc2`: is this the raw descriptor data from the CUDA module? If yes, it won't work with that indexing: remember `desc2` is raw memory with 64 byte (512-bit) descriptor data

**Comment by antithing** [comment]
Hi! Thank you for getting back to me. In Matcher.hpp, i have added:

```
	void setMapData(int kpNum, std::vector<uint64_t> const &desc)
	{
		cudaMemsetAsync(d_descM, 0, 64 * (kpNum + 8), m_stream1);
		cudaMemcpyAsync(d_descM, &desc[0], 64 * (kpNum + 8), cudaMemcpyHostToDevice, m_stream1);
		cudaStreamSynchronize(m_stream1);

		this->kpMap = kpNum;
	}


	void matchFeaturesWithMap()
	{
		cudaMemset(d_matches, 0, static_cast<int>(kpQuery));
		auto start = std::chrono::high_resolution_clock::now();
		CUDAK2NN(d_descM, static_cast<int>(kpMap), tex_q, static_cast<int>(kpQuery), d_matches, matchThreshold);
		auto end = std::chrono::high_resolution_clock::now();

		std::vector<int> h_matches(kpQuery);
		cudaMemcpy(&h_matches[0], d_matches, 4 * kpQuery, cudaMemcpyDeviceToHost);
		mmatches.clear();
		for (size_t i = 0; i < kpQuery; ++i) {
			if (h_matches[i] != -1) {
				mmatches.emplace_back(h_matches[i], i, 0.0f);
			}
		}
		auto sec = static_cast<double>(duration_cast<std::chrono::nanoseconds>(end - start).count()) * 1e-9 / static_cast<double>(1);
		std::cout << "Computed " << mmatches.size() << " matches in " << sec * 1e3 << " ms" << std::endl;

	}

	void matchSceneWithMap(std::vector<Keypoint> const &kps, std::vector<uint64_t> const &desc)
	{
		setQueryImage(kps, desc);
		matchFeaturesWithMap(); // fills mmatches vector
	}
```

In my main.cpp, I have:

```
	std::vector <cv::KeyPoint> kpsL, kpsR;
	std::vector<uint64_t> desc1;
	std::vector<uint64_t> desc2;

	std::vector<cv::KeyPoint> localMap_kp;
	std::vector<uint64_t> localMap_desc;

KFeatureDetector detector(scaleFactor, scaleLevels, width, height, maxFeatureCount, fastThreshold);
	KFeatureMatcher matcher(matchThreshold, maxFeatureCount);
	
	auto start = high_resolution_clock::now();

	

	detector.extractFeatures(img1);
	matcher.setTrainingImage(detector.kps, detector.desc);

	kpsL = detector.converted_kps;
	desc1 = detector.desc;


	detector.extractFeatures(img2);
	matcher.setQueryImage(detector.kps, detector.desc);

	kpsR = detector.converted_kps;
	desc2 = detector.desc;
	
	matcher.matchFeatures();

```
Then, to get the first 10 keypoints and descriptors (for example) I am doing this:

```
	std::copy(kpsR.begin(), kpsR.begin() + 10, std::back_inserter(localMap_kp));
	std::copy(desc2.begin(), desc2.begin() + (10 * 8), std::back_inserter(localMap_desc));
```

This SEEMS to be working, and copying the 10 kps and matching descriptor data to a new vector. But is it correct? Or am i better off using memcpy? Thank you again for your time!



... to add to a map and test using the first image keypoints again,, I am doing:

   ```
     matcher.setMapData(localMap_kp.size(), localMap_desc);


	//match to this map
	detector.extractFeatures(img1);
	kpsL = detector.converted_kps;
	matcher.matchSceneWithMap(detector.kps, detector.desc);
```

Which I THINK is ok, does this make sense?

**Comment by saihv** [comment]
I am a little confused by what you're attempting to do. Do you want to 

A) Retrieve only the first ten descriptors from a given detection result, or
B) Do A, AND then use those ten descriptors as a new map?

```
std::copy(kpsR.begin(), kpsR.begin() + 10, std::back_inserter(localMap_kp));
std::copy(desc2.begin(), desc2.begin() + (10 * 8), std::back_inserter(localMap_desc));
```

This means you're attempting to copy 80 `uint64` elements from desc2 into localMap_desc: which I am assuming is not what you want. If you're trying to use those 10 features as seed features for some future matching, you should only copy 10 elements into localMap_desc: but when you're allocating CUDA memory for this, you have to pad this 10 element descriptor data with 8 extra elements, which is why you'd have to do 64 * (10 + 8).

**Comment by antithing** [comment]
Hi, thanks for your patience. Basically I am just trying to figure out how to get the corresponding descriptor for a certain keypoint (or range of keypoints).

The desc vector after running KORAL is 8 x the size of the keypoint vector, so I am assuming that the first 8 uint64_t elements of the vector make up ONE descriptor. 

after testing this, it does seem to work, I just want to check i am not looking at this all wrong. 

Thanks again!

**Comment by saihv** [comment]
My bad! Yes, you're right, I completely somehow skipped over the fact that the vector only has 64 bytes in each element. And then yes, copying 80 elements should work.

**Comment by antithing** [comment]
Okay awesome. Thanks again! Closing the issue.
